spring:
  application:
    name: "@project.name@"
    version: "@project.version@"
  profiles:
    active: prod

logging:
  charset:
    file: UTF-8
    console: UTF-8
  file:
    path: ./logs

application:
  input:
  config: