spring:
  application:
    name: ad-filters-subscriber
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 6 #警告阈值, 原始规则长度小于该值时会输出警告日志

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:
      - name: 'Subscription 1'
        path: 'https://example.org/rule.txt' #仅支持 http/https，不限定响应内容格式

      - name: 'Subscription 2'
        path: 'http://example.org/rule.txt'

    #本地规则文件
    local:
      - name: 'local rule'
        path: 'local-rule.txt' #支持绝对/相对路径

  #输出配置
  output:
    #生成的规则文件头部内容, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
    file_header: |
      [ADFS Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/fordes123/ad-filters-subscriber/

    path: rule #输出规则文件的路径，支持绝对/相对路径
    #输出规则文件列表 （！注意缩进）
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则
        - MODIFY  #修饰规则，添加了一些修饰符号的规则
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
